# Generated by Django 5.0.3 on 2024-05-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('deptid', models.IntegerField(primary_key=True, serialize=False)),
                ('deptname', models.CharField(max_length=100, unique=True)),
                ('deptloc', models.CharField(max_length=100)),
            ],
        ),
    ]
