# Generated by Django 5.0.3 on 2024-05-17 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_sal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job', models.CharField(max_length=100)),
                ('hire_date', models.DateField()),
                ('coomition', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deptid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
                ('mgr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.emp')),
            ],
        ),
    ]
